theme: jekyll-theme-midnight
title: sebastian4j.github.io
description: "Contenido dedicado principalmente a Java :coffee: con el ecosistema que lo rodea: microProfile, Jakarta, Spring, JPMS, JPA, ..."
